### ISSUE TITLE
_check_leading_expression:19: failed to compile regex: empty (sub)expression

### ISSUE THREAD

**Issue by derimagia** [jimmijj/chromatic-zsh#1]
Getting this error when using a fresh zsh script (removed my stuff from zshrc and zprofile) as well as.

Using a mac so with this version of zsh:

> zsh 5.2 (x86_64-apple-darwin15.0.0)

Some of the characters are syntax colored depending on what I type, typing just gipperish making it error on every character.

I'm also getting this error WITH my zsh config set:

> _check_leading_expression:7: bad math expression: operator expected at `images doc...'

But that may be a setting for zsh I need to enable to match yours

**Comment by derimagia** [comment]
Part of the reason for this is __chromatic_attrib_zle is not in the correct scrope - needs to be global.

**Comment by jimmijj** [comment]
What exactly do you type into terminal to get these errors? I cannot reproduce neither of them. Does it happen if you source chromatic-zsh after 'zsh -f'?

**Comment by dezza** [comment]
I get this on FreeBSD as well.

It happens on every keystroke.

I use zplug to load it. I tried to load it as the single plugin and it still happens.

`freebsd% l
_check_leading_expression:19: failed to compile regex: empty (sub)expression
freebsd% ls
freebsd% d
_check_leading_expression:19: failed to compile regex: empty (sub)expression
freebsd% da
_check_leading_expression:19: failed to compile regex: empty (sub)expression
freebsd% dad
_check_leading_expression:19: failed to compile regex: empty (sub)expression
freebsd% da
_check_leading_expression:19: failed to compile regex: empty (sub)expression
freebsd% d
_check_leading_expression:19: failed to compile regex: empty (sub)expression
freebsd%
`

**Comment by jimmijj** [comment]
@dezza @derimagia After some investigation it seems that regexp module behaves differently on different systems. Some of them don't accept pipe at the beginning of (sub)expression like `foo(|bar)baz`and throw above error. I've rearranged the code in this regards, please report if it works now.

**Comment by derimagia** [comment]
The first error is fixed so now I keep getting the second one - 

if I type an alias I get "_check_leading_expression:7: bad math expression: operator expected at `images cl ...'"

Other times I get "_check_subsequent_expression:4: bad math expression: operator expected at `on off off...'" - looks to be something off it doesn't like about the case statements

**Comment by dezza** [comment]
Same experience as @derimagia

`_check_leading_expression:11: bad math expression: operator expected at `defined de...'`

Is another one reproduced by for example typing `source`

`zsh --version
zsh 5.2 (amd64-portbld-freebsd10.1)`
`uname -a
FreeBSD freebsd 10.3-RELEASE-p4 FreeBSD 10.3-RELEASE-p4 #0: Sat May 28 12:23:44 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64`
